// errors/error-codes.js
// Centralized Error Code Constants

export const ErrorCodes = {
    // Media Processing Errors (1000-1999)
    MEDIA_PROCESSING: {
        FAILED_TO_PROCESS: 'MEDIA_1001',
        INVALID_URL: 'MEDIA_1002',
        UNSUPPORTED_FORMAT: 'MEDIA_1003',
        DURATION_LIMIT_EXCEEDED: 'MEDIA_1004',
        VIDEO_UNAVAILABLE: 'MEDIA_1005',
        RESTRICTED_VIDEO: 'MEDIA_1006',
        NO_VIDEO_ID: 'MEDIA_1007',
        FAILED_TO_GET_VIDEO_INFO: 'MEDIA_1008',
        FAILED_TO_DOWNLOAD: 'MEDIA_1009',
        FAILED_TO_PROCESS_AUDIO: 'MEDIA_1010',
        PRELOADED_FILE_NOT_FOUND: 'MEDIA_1011',
        YT_DLP_TIMEOUT: 'MEDIA_1012',
        YT_DLP_BINARY_NOT_FOUND: 'MEDIA_1013'
    },

    // Session Errors (2000-2999)
    SESSION: {
        NO_ACTIVE_SESSION: 'SESSION_2001',
        SESSION_CREATION_FAILED: 'SESSION_2002',
        VOICE_CONNECTION_FAILED: 'SESSION_2003',
        PERMISSION_DENIED: 'SESSION_2004',
        CHANNEL_NOT_FOUND: 'SESSION_2005',
        MEMBER_NOT_FOUND: 'SESSION_2006',
        BOT_NOT_IN_VOICE: 'SESSION_2007',
        INVALID_VOICE_STATE: 'SESSION_2008',
        SESSION_ALREADY_EXISTS: 'SESSION_2009',
        SESSION_CLEANUP_FAILED: 'SESSION_2010',
        USER_NOT_IN_VOICE: 'SESSION_2011'
    },

    // Queue Errors (3000-3999)
    QUEUE: {
        QUEUE_FULL: 'QUEUE_3001',
        SONG_ALREADY_IN_QUEUE: 'QUEUE_3002',
        QUEUE_EMPTY: 'QUEUE_3003',
        INVALID_QUEUE_POSITION: 'QUEUE_3004',
        QUEUE_ADDITION_FAILED: 'QUEUE_3005',
        QUEUE_REMOVAL_FAILED: 'QUEUE_3006',
        QUEUE_CLEAR_FAILED: 'QUEUE_3007',
        PRELOAD_FAILED: 'QUEUE_3008'
    },

    // Validation Errors (4000-4999)
    VALIDATION: {
        INVALID_GUILD_ID: 'VALIDATION_4001',
        INVALID_CHANNEL_ID: 'VALIDATION_4002',
        INVALID_USER_ID: 'VALIDATION_4003',
        INVALID_QUERY: 'VALIDATION_4004',
        INVALID_SPOTIFY_URL: 'VALIDATION_4005',
        INVALID_YOUTUBE_URL: 'VALIDATION_4006',
        INVALID_PLAYLIST_URL: 'VALIDATION_4007',
        MISSING_REQUIRED_FIELD: 'VALIDATION_4008',
        INVALID_DURATION: 'VALIDATION_4009',
        INVALID_VOLUME: 'VALIDATION_4010',
        // Modal Validation Errors
        EMPTY_SONG_QUERY: 'VALIDATION_4011',
        SONG_PROCESSING_FAILED: 'VALIDATION_4012',
        MODAL_PROCESSING_ERROR: 'VALIDATION_4013'
    },

    // Network Errors (5000-5999)
    NETWORK: {
        REQUEST_TIMEOUT: 'NETWORK_5001',
        CONNECTION_FAILED: 'NETWORK_5002',
        API_RATE_LIMITED: 'NETWORK_5003',
        API_UNAVAILABLE: 'NETWORK_5004',
        INVALID_RESPONSE: 'NETWORK_5005',
        AUTHENTICATION_FAILED: 'NETWORK_5006',
        PERMISSION_DENIED: 'NETWORK_5007',
        RESOURCE_NOT_FOUND: 'NETWORK_5008',
        SERVER_ERROR: 'NETWORK_5009',
        DISCORD_API_ERROR: 'NETWORK_5010'
    },

    // Database Errors (6000-6999)
    DATABASE: {
        CONNECTION_FAILED: 'DATABASE_6001',
        QUERY_FAILED: 'DATABASE_6002',
        TRANSACTION_FAILED: 'DATABASE_6003',
        RECORD_NOT_FOUND: 'DATABASE_6004',
        DUPLICATE_RECORD: 'DATABASE_6005',
        CONSTRAINT_VIOLATION: 'DATABASE_6006',
        MIGRATION_FAILED: 'DATABASE_6007'
    },

    // System Errors (7000-7999)
    SYSTEM: {
        MEMORY_LIMIT_EXCEEDED: 'SYSTEM_7001',
        FILE_SYSTEM_ERROR: 'SYSTEM_7002',
        PROCESS_CREATION_FAILED: 'SYSTEM_7003',
        PROCESS_KILL_FAILED: 'SYSTEM_7004',
        TEMP_FILE_CLEANUP_FAILED: 'SYSTEM_7005',
        RESOURCE_CLEANUP_FAILED: 'SYSTEM_7006',
        CONFIGURATION_ERROR: 'SYSTEM_7007',
        ENVIRONMENT_ERROR: 'SYSTEM_7008'
    },

    // Discord API Errors (8000-8999)
    DISCORD: {
        UNKNOWN_MESSAGE: 'DISCORD_8001',
        UNKNOWN_CHANNEL: 'DISCORD_8002',
        UNKNOWN_GUILD: 'DISCORD_8003',
        UNKNOWN_USER: 'DISCORD_8004',
        MISSING_PERMISSIONS: 'DISCORD_8005',
        INVALID_FORM_BODY: 'DISCORD_8006',
        INTERACTION_EXPIRED: 'DISCORD_8007',
        INTERACTION_ALREADY_ACKNOWLEDGED: 'DISCORD_8008',
        WEBHOOK_NOT_FOUND: 'DISCORD_8009',
        WEBHOOK_EXPIRED: 'DISCORD_8010'
    }
};

// Flattened error codes for easy access
export const FLATTENED_ERROR_CODES = Object.values(ErrorCodes).reduce((acc, category) => {
    return { ...acc, ...category };
}, {});
